#! /bin/sh

# exit immediately on error
set -e

psql -q -c "CREATE USER coffee_user SUPERUSER PASSWORD '123'"
echo "Created Postgres user 'coffee_user'"

psql -q -c "CREATE DATABASE coffee_db WITH OWNER coffee_user"
echo "Created Postgres database 'coffee_db'"

cp -n example.env .env
echo "Created .env with database URL"